version: "3"
services:
  master:
    container_name: master
    image: jenkins/jenkins:latest
    ports:
      - 8080:8080
    volumes: 
      - ./jenkins_home:/var/jenkins_home
    links:
      - slave01

  slave01:
    container_name: slave01
    image: jenkins/ssh-slave
    environment: 
        - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3.......zt
